# FILE: app/db/__init__.py
# DESCRIPTION: Database layer package with modernized structure.

from __future__ import annotations

# Core connection layer
from app.db.connection import (
    get_sync_pool,
    get_async_pool,
    close_sync_pool,
    close_async_pool,
    PgSession,
    AsyncPgSession,
    pg_fetchone,
    pg_fetchall,
    pg_execute,
    pg_exists,
    pg_scalar,
    pg_fetchone_async,
    pg_fetchall_async,
    pg_execute_async,
    pg_exists_async,
    pg_scalar_async,
    vector_sql,
)

# SQL queries and constants
from app.db.queries import (
    TOOL_ROLES,
    ALL_TOOL_ROLES,
    tool_role_for,
    encrypt_api_key,
    decrypt_api_key,
    DECRYPTION_ERROR,
    SCHEMA_DDL,
    SQL_PROFILE_SELECT_FIRST,
    SQL_PROFILE_INSERT_DEFAULT,
    DEFAULT_PROFILE_PARAMS,
    build_profile_update,
    parse_profile_row,
    SQL_SESSION_SELECT_ACTIVE,
    SQL_SESSION_INSERT,
    SQL_SESSION_SELECT_ALL,
    SQL_SESSION_DEACTIVATE_ALL,
    SQL_SESSION_ACTIVATE_ONE,
    SQL_SESSION_RENAME,
    SQL_SESSION_DELETE,
    SQL_SESSION_UPDATE_MEMORY,
    SQL_SESSION_INCREMENT_COUNT,
    SQL_SESSION_RESET_COUNT_AND_MEMORY,
    parse_session_row,
    SQL_SESSION_MEMORY_NOTES,
    parse_session_memory_rows,
    SQL_APIKEY_SELECT_ALL,
    SQL_APIKEY_SELECT_BY_NAME,
    SQL_APIKEY_SELECT_ID_BY_NAME,
    SQL_APIKEY_UPDATE,
    SQL_APIKEY_INSERT,
    SQL_APIKEY_DELETE,
    decrypt_api_key_rows,
    SQL_MESSAGE_INSERT,
    SQL_MESSAGE_SELECT_ASC_LIMIT,
    SQL_MESSAGE_SELECT_DESC_LIMIT,
    SQL_MESSAGE_SELECT_ASC_ALL,
    SQL_MESSAGE_DELETE_FOR_SESSION,
    SQL_MESSAGE_COUNT_CONVERSATIONAL,
    SQL_MESSAGE_RECENT_SYSTEM_GLOBAL,
    SQL_MESSAGE_RECENT_SYSTEM_FOR_SESSION,
    SQL_MESSAGE_CONVERSATION_SUMMARY,
    SQL_MESSAGE_HISTORY_FOR_AI_ASC_LIMIT,
    SQL_MESSAGE_HISTORY_FOR_AI_DESC_LIMIT,
    SQL_MESSAGE_HISTORY_FOR_AI_ASC_ALL,
    SQL_MESSAGE_SELECT_ENCRYPTED,
    SQL_MESSAGE_SELECT_CONTENT_BY_ID,
    SQL_MESSAGE_UPDATE_DECRYPTED,
    parse_message_row,
    parse_event_row,
    format_conversation_summary,
    format_ai_history_rows,
    extract_command_from_markdown_contract,
    extract_raw_result_from_markdown_contract,
    SQL_ENC_TOTAL_MESSAGES,
    SQL_ENC_ENCRYPTED_MESSAGES,
    SQL_ENC_TOTAL_KEYS,
    SQL_ENC_ENCRYPTED_KEYS,
    build_encryption_status,
    parse_json,
    format_session_event,
)

# Sync models
from app.db.models import (
    init_pg_tables,
    get_profile,
    update_profile,
    get_context,
    update_context,
    get_memory,
    update_memory,
    get_active_session,
    get_all_sessions,
    create_session,
    switch_session,
    rename_session,
    delete_session,
    get_session_memory,
    update_session_memory,
    increment_message_count,
    get_memory_state,
    update_memory_state,
    get_api_keys,
    get_api_key,
    add_api_key,
    remove_api_key,
    add_message,
    get_session_messages,
    get_recent_messages,
    get_chat_history,
    clear_session_messages,
    get_message_count,
    add_session_event,
    get_recent_sessions,
    get_recent_sessions_for_session,
    get_session_conversation_summary,
    add_image_tools_message,
    add_tool_result,
    add_system_note,
    add_memory_note,
    get_chat_history_for_ai,
    get_encryption_status,
    get_all_encrypted_messages,
    batch_decrypt_messages,
)

# Async models
from app.db.models_async import (
    init_pg_tables_async,
    get_profile_async,
    update_profile_async,
    get_context_async,
    update_context_async,
    get_memory_async,
    update_memory_async,
    get_active_session_async,
    get_all_sessions_async,
    create_session_async,
    switch_session_async,
    rename_session_async,
    delete_session_async,
    get_session_memory_async,
    update_session_memory_async,
    increment_message_count_async,
    get_api_keys_async,
    get_api_key_async,
    add_api_key_async,
    remove_api_key_async,
    add_message_async,
    get_session_messages_async,
    get_recent_messages_async,
    get_chat_history_async,
    clear_session_messages_async,
    get_message_count_async,
    add_session_event_async,
    get_recent_sessions_async,
    get_recent_sessions_for_session_async,
    get_session_conversation_summary_async,
    add_image_tools_message_async,
    add_tool_result_async,
    add_system_note_async,
    add_memory_note_async,
    get_chat_history_for_ai_async,
    get_encryption_status_async,
    get_all_encrypted_messages_async,
    batch_decrypt_messages_async,
)

# Facade
from app.db.facade import Database, init_db
